<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// search/bar.phtml -- rendered by Ampache\Gui\Search\SearchBarView

/** @var Ampache\Gui\Search\SearchBarView $this */
?>
<div id="sb_Subsearch">
    <form name="search" method="post" action="<?php echo $this->e($this->getFormAction()); ?>" enctype="multipart/form-data">
        <input type="text" name="rule_1_input" id="searchString" placeholder="<?php echo $this->e(T_('Search')); ?>" />
        <input type="hidden" name="action" value="search" />
        <input type="hidden" name="rule_1_operator" value="0" />
        <input type="hidden" name="object_type" value="song" />
        <select name="rule_1" id="searchStringRule">
            <?php foreach ($this->getOptions() as $option) { ?>
            <option value="<?php echo $this->e($option['value']); ?>"><?php echo $this->e($option['label']); ?></option>
            <?php } ?>
        </select>
        <input class="button" type="submit" value="<?php echo $this->e(T_('Search')); ?>" id="searchBtn"<?php echo ($this->isMobile()) ? ' style="display: none;"' : ''; ?> />
    </form>
</div>
