<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PreferencesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seeds = array(['name' => 'download', 'value' => '1', 'description' => 'Allow Downloads',
            'level' => 100, 'type' => 'boolean', 'category' => 'optionss', 'subcategory' => 'feature'],
            ['name' => 'popular_threshold', 'value' => '10', 'description' => 'Popular Threshold',
                'level' => 25, 'type' => 'integer', 'category' => 'interface', 'subcategory' => 'query'],

            ['name' => 'transcode_bitrate', 'value' => '64', 'description' => 'Transcode Bitrate',
                'level' => 25, 'type' => 'string', 'category' => 'Streaming', 'subcategory' => 'transcodeng'],

            ['name' => 'site_title', 'value' => "Ampache :: For the love of Music", 'description' => 'Website Title',
                'level' => 100, 'type' => 'string', 'category' => 'interface', 'subcategory' => 'custom'],
            ['name' => 'lock_songs', 'value' => '0', 'description' => 'Lock Songs',
                'level' => 25, 'type' => 'integer', 'category' => 'system', 'subcategory' => ''],
            ['name' => 'force_http_play', 'value' => '0', 'description' => 'Forces Http play regardless of port',
                'level' => 100, 'type' => 'booleanr', 'category' => 'system', 'subcategory' => ''],
            ['name' => 'localplay_controller', 'value' => '0', 'description' => 'Localplay Type',
                'level' => 100, 'type' => 'special', 'category' => 'optionss', 'subcategory' => 'localplay'],
            ['name' => 'play_type', 'value' => 'web_player', 'description' => 'Type of Playback',
                'level' => 25, 'type' => 'special', 'category' => 'streaming', 'subcategory' => ''],
            ['name' => 'lang', 'value' => 'en_US', 'description' => 'Language',
                'level' => 100, 'type' => 'special', 'category' => 'interface', 'subcategory' => 'theme'],
            ['name' => 'playlist_type', 'value' => 'm3u', 'description' => 'Playlist Type',
                'level' => 100, 'type' => 'boolean', 'category' => 'special', 'subcategory' => ''],
            ['name' => 'theme_name', 'value' => 'reborn', 'description' => 'Theme',
                'level' => 0, 'type' => 'special', 'category' => 'interface', 'subcategory' => 'query'],
            ['name' => 'offset_limit', 'value' => '50', 'description' => 'Offset Limit',
                'level' => 5, 'type' => 'integer', 'category' => 'interface', 'subcategory' => 'query'],
            ['name' => 'localplay_level', 'value' => '0', 'description' => 'Localplay Access',
                'level' => 100, 'type' => 'special', 'category' => 'optionss', 'subcategory' => 'localplay'],
            ['name' => 'allow_stream_playback', 'value' => '1', 'description' => 'Allow Streaming',
                'level' => 100, 'type' => 'boolean', 'category' => 'optionss', 'subcategory' => 'feature'],
            ['name' => 'allow_democratic_playback', 'value' => '0', 'description' => 'Allow Democratic Play',
                'level' => 100, 'type' => 'boolean', 'category' => 'optionss', 'subcategory' => 'feature'],
            ['name' => 'allow_localplay_playback', 'value' => '0', 'description' => 'Allow Localplay Play',
                'level' => 100, 'type' => 'boolean', 'category' => 'optionss', 'subcategory' => 'localplay'],
            ['name' => 'stats_threshold', 'value' => '7', 'description' => 'Statistics Day Threshold',
                'level' => 25, 'type' => 'integer', 'category' => 'interface', 'subcategory' => 'query'],
            ['name' => 'rate_limit', 'value' => '8192', 'description' => 'Rate Limit',
                'level' => 100, 'type' => 'integer', 'category' => 'streaming', 'subcategory' => 'transcoding'],
            ['name' => 'playlist_method', 'value' => 'default', 'description' => 'Playlist Method',
                'level' => 5, 'type' => 'string', 'category' => 'playlist', 'subcategory' => ''],
            ['name' => 'transcode', 'value' => 'default', 'description' => 'Transcoding',
                'level' => 25, 'type' => 'string', 'category' => 'streaming', 'subcategory' => 'transcoding'],
            ['name' => 'show_lyrics', 'value' => '0', 'description' => 'Show Lyrics',
                'level' => 0, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'player'],
            ['name' => 'mpd_active', 'value' => '0', 'description' => 'MPD Active Instance',
                'level' => 25, 'type' => 'integer', 'category' => 'internal', 'subcategory' => 'mpd'],
            ['name' => 'httpq_active', 'value' => '0', 'description' => 'HTTPQ Active Instance',
                'level' => 25, 'type' => 'integer', 'category' => 'internal', 'subcategory' => 'httpq'],
            ['name' => 'shoutcast_active', 'value' => '0', 'description' => 'Shoutcast Active Instance',
                'level' => 25, 'type' => 'integern', 'category' => 'internal', 'subcategory' => 'shoutcast'],
            ['name' => 'lastfm_grant_link', 'value' => '', 'description' => "Last.FM Grant URL",
                'level' => 25, 'type' => 'string', 'category' => 'internal', 'subcategory' => 'lastfm'],
            ['name' => 'lastfm_challenge', 'value' => '', 'description' => 'Last.FM Submit Challenge',
                'level' => 25, 'type' => 'string', 'category' => 'internal', 'subcategory' => 'lastfm'],
            ['name' => 'share', 'value' => '0', 'description' => 'Allow Share',
                'level' => 100, 'type' => 'boolean', 'category' => 'optionss', 'subcategory' => 'feature'],
           ['name' => 'ajax_load', 'value' => '1', 'description' => 'Ajax page load',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => ''],
            ['name' => 'now_playing_per_user', 'value' => '1', 'description' => 'Now playing filtered per user',
                'level' => 250, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'home'],
            ['name' => 'album_sort', 'value' => '0', 'description' => 'Album Default Sort',
                'level' => 25, 'type' => 'string', 'category' => 'interface', 'subcategory' => 'library'],
            ['name' => 'show_played_times', 'value' => '0', 'description' => 'Show # played',
                'level' => 25, 'type' => 'string', 'category' => 'interface', 'subcategory' => 'library'],
            ['name' => 'song_page_title', 'value' => '1', 'description' => 'Show current song in Web player page title',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'player'],
            ['name' => 'subsonic_backend', 'value' => '1', 'description' => 'Use SubSonic backend',
                'level' => 100, 'type' => 'boolean', 'category' => 'system', 'subcategory' => 'backend'],
            ['name' => 'plex_backend', 'value' => '0', 'description' => 'Use Plex backend',
                'level' => 100, 'type' => 'boolean', 'category' => 'system', 'subcategory' => 'backend'],
            ['name' => 'webplayer_flash', 'value' => '1', 'description' => 'Authorize Flash Web Player(s)',
                'level' => 25, 'type' => 'boolean', 'category' => 'streaming', 'subcategory' => 'player'],
            ['name' => 'webplayer_html5', 'value' => '1', 'description' => 'Authorize HTML5 Web Player(s)',
                'level' => 25, 'type' => 'boolean', 'category' => 'streaming', 'subcategory' => 'player'],
            ['name' => 'allow_personal_info_now', 'value' => '1', 'description' => 'Personal information visibility - Now playing',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'privacy'],
            ['name' => 'allow_personal_info_recent', 'value' => '1', 'description' => 'Personal information visibility - Recently played',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'privacy'],
            ['name' => 'allow_personal_info_time', 'value' => '1', 'description' => 'Personal information visibility - Recently played - Allow to show streaming date/time',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'privacy'],
            ['name' => 'allow_personal_info_agent', 'value' => '1', 'description' => 'Personal information visibility - Recently played - Allow to show streaming agent',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'privacy'],
            ['name' => 'ui_fixed', 'value' => '0', 'description' => 'Fix header position on compatible themes',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'theme'],
            ['name' => 'autoupdate', 'value' => '1', 'description' => 'Check for Ampache updates automatically',
                'level' => 25, 'type' => 'boolean', 'category' => 'system', 'subcategory' => 'update'],
            ['name' => 'autoupdate_lastcheck', 'value' => '', 'description' => 'AutoUpdate last check time',
                'level' => 25, 'type' => 'string', 'category' => 'internal', 'subcategory' => 'update'],
            ['name' => 'autoupdate_lastversion', 'value' => '', 'description' => 'AutoUpdate last version from last check',
                'level' => 25, 'type' => 'string', 'category' => 'internal', 'subcategory' => 'update'],
            ['name' => 'autoupdate_lastversion_new', 'value' => '', 'description' => 'AutoUpdate last version from last check is newer',
                'level' => 25, 'type' => 'string', 'category' => 'internal', 'subcategory' => 'update'],
            ['name' => 'webplayer_pausetabs', 'value' => '1', 'description' => 'Auto-pause betweens tabs',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'player'],
            ['name' => 'tream_beautiful_url', 'value' => '1', 'description' => 'Enable url rewriting',
               'level' => 100, 'type' => 'boolean', 'category' => 'streaming', 'subcategory' => ''],
            ['name' => 'share_expire', 'value' => '7', 'description' => 'Share links default expiration days (0=never)',
                'level' => 100, 'type' => 'integer', 'category' => 'system', 'subcategory' => 'share'],
            ['name' => 'slideshow_time', 'value' => '0', 'description' => 'Artist slideshow inactivity time',
                'level' => 25, 'type' => 'integer', 'category' => 'interface', 'subcategory' => 'player'],
            ['name' => 'broadcast_by_default', 'value' => '0', 'description' => 'Broadcast web player by default',
                'level' => 25, 'type' => 'boolean', 'category' => 'streaming', 'subcategory' => 'player'],
            ['name' => 'concerts_limit_future', 'value' => '0', 'description' => 'Limit number of future events',
                'level' => 25, 'type' => 'integer', 'category' => 'interface', 'subcategory' => 'query'],
            ['name' => 'album_group', 'value' => '0', 'description' => 'Album - Group multiple disks',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'library'],
            ['name' => 'topmenu', 'value' => '0', 'description' => 'Top menu',
                'level' => 25, 'type' => 'integer', 'category' => 'interface', 'subcategory' => 'theme'],
            ['name' => 'demo_clear_sessions', 'value' => '0', 'description' => 'Clear democratic votes of expired user sessions',
                'level' => 25, 'type' => 'integer', 'category' => 'playlist', 'subcategory' => ''],
            ['name' => 'show_donate', 'value' => '1', 'description' => 'Show donate button in footer',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => ''],
            ['name' => 'upload_catalog', 'value' => '-1', 'description' => 'Uploads catalog destination',
                'level' => 75, 'type' => 'integer', 'category' => 'system', 'subcategory' => 'upload'],
            ['name' => 'allow_upload', 'value' => '0', 'description' => 'Allow users to upload media',
                'level' => 75, 'type' => 'boolean', 'category' => 'system', 'subcategory' => 'upload'],
            ['name' => 'upload_subdir', 'value' => '1', 'description' => 'Upload: create a subdirectory per user (recommended)',
                'level' => 75, 'type' => 'boolean', 'category' => 'system', 'subcategory' => 'upload'],
           ['name' => 'upload_user_artist', 'value' => '0', 'description' => 'Upload: consider the user sender as the track\'s artist',
                'level' => 75, 'type' => 'boolean', 'category' => 'system', 'subcategory' => 'upload'],
            ['name' => 'upload_script', 'value' => '', 'description' => 'Upload: run the following script after upload (current directory = upload target directory)',
                'level' => 75, 'type' => 'string', 'category' => 'system', 'subcategory' => 'upload'],
            ['name' => 'upload_allow_edit', 'value' => '1', 'description' => 'Upload: allow users to edit uploaded songs',
                'level' => 75, 'type' => 'boolean', 'category' => 'system', 'subcategory' => 'upload'],
            ['name' => 'daap_backend', 'value' => '1', 'description' => 'Use DAAP backend',
                'level' => 100, 'type' => 'boolean', 'category' => 'system', 'subcategory' => 'backend'],
            ['name' => 'daap_pass', 'value' => '', 'description' => 'DAAP backend password',
                'level' => 100, 'type' => 'string', 'category' => 'system', 'subcategory' => 'backend'],
            ['name' => 'upnp_backend', 'value' => '1', 'description' => 'Use UPnP backend',
                'level' => 100, 'type' => 'boolean', 'category' => 'system', 'subcategory' => 'backend'],
            ['name' => 'allow_video', 'value' => '1', 'description' => 'Allow video features',
                'level' => 100, 'type' => 'boolean', 'category' => 'optionss', 'subcategory' => 'feature'],
            ['name' => 'album_release_type', 'value' => '1', 'description' => 'Album - Group per release type',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'library'],
            ['name' => 'direct_play_limit', 'value' => '0', 'description' => 'Limit direct play to maximum media count',
                'level' => 25, 'type' => 'string', 'category' => 'interface', 'subcategory' => 'player'],
            ['name' => 'home_moment_albums', 'value' => '1', 'description' => 'Show Albums of the moment at home page',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'home'],
            ['name' => 'home_moment_videos', 'value' => '1', 'description' => 'Show Videos of the moment at home page',
                'level' => 25, 'type' => 'boolean', 'category' => 'system', 'subcategory' => 'backend'],
            ['name' => 'home_recently_played', 'value' => '1', 'description' => 'Show Recently Played at home page',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'home'],
            ['name' => 'home_now_playing', 'value' => '1', 'description' => 'Show Now Playing on home page',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'home'],
            ['name' => 'custom_logo', 'value' => '', 'description' => 'Custom logo url',
                'level' => 25, 'type' => 'string', 'category' => 'system', 'subcategory' => 'custom'],
            ['name' => 'album_release_type_sort', 'value' => 'album,ep,live,single', 'description' => 'Album - Group per release type Sort',
                'level' => 25, 'type' => 'string', 'category' => 'interface', 'subcategory' => 'library'],
            ['name' => 'browser_notify', 'value' => '1', 'description' => 'WebPlayer browser notifications',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'notification'],
            ['name' => 'browser_notify_timeout', 'value' => '10', 'description' => 'WebPlayer browser notifications timeout (seconds)',
                'level' => 25, 'type' => 'integer', 'category' => 'interface', 'subcategory' => 'notification'],
            ['name' => 'geolocation', 'value' => '0', 'description' => 'Allow geolocation',
                'level' => 25, 'type' => 'boolean', 'category' => 'optionss', 'subcategory' => 'feature'],
            ['name' => 'webplayer_aurora', 'value' => '1', 'description' => 'Authorize JavaScript decoder (Aurora.js) in Web Player(s)',
                'level' => 25, 'type' => 'boolean', 'category' => 'streaming', 'subcategory' => 'player'],
            ['name' => 'upload_allow_remove', 'value' => '1', 'description' => 'Upload: allow users to remove uploaded songs',
                'level' => 75, 'type' => 'boolean', 'category' => 'system', 'subcategory' => 'upload'],
            ['name' => 'custom_favicon', 'value' => '', 'description' => 'Custom favicon url',
                'level' => 75, 'type' => 'string', 'category' => 'interface', 'subcategory' => 'custom'],
            ['name' => 'custom_text_footer', 'value' => '', 'description' => 'Custom text footer',
                'level' => 75, 'type' => 'string', 'category' => 'interface', 'subcategory' => 'custom'],
            ['name' => 'webdav_backend', 'value' => '0', 'description' => 'Use WebDAV backend',
                'level' => 100, 'type' => 'boolean', 'category' => 'system', 'subcategory' => 'backend'],
            ['name' => 'notify_email', 'value' => '0', 'description' => 'Receive notifications by email (shouts, private messages, ...)',
                'level' => 25, 'type' => 'boolean', 'category' => 'options', 'subcategory' => ''],
            ['name' => 'theme_color', 'value' => 'dark', 'description' => 'Theme color',
                'level' => 0, 'type' => 'special', 'category' => 'interface', 'subcategory' => 'theme'],
            ['name' => 'disabled_custom_metadata_fields', 'value' => '', 'description' => 'Disable custom metadata fields (ctrl / shift click to select multiple)',
                'level' => 100, 'type' => 'string', 'category' => 'system', 'subcategory' => 'custom'],
            ['name' => 'disabled_custom_metadata_fields_input', 'value' => '', 'description' => 'Disable custom metadata fields. Insert them in a comma separated list. They will add to the fields selected above.',
                'level' => 100, 'type' => 'string', 'category' => 'system', 'subcategory' => 'metadata'],
            ['name' => 'podcast_keep', 'value' => '10', 'description' => 'Podcast: # latest episodes to keep',
                'level' => 100, 'type' => 'integer', 'category' => 'system', 'subcategory' => 'podcast'],
           ['name' => 'podcast_new_download', 'value' => '1', 'description' => 'Podcast: # episodes to download when new episodes are available',
                'level' => 100, 'type' => 'integer', 'category' => 'system', 'subcategory' => 'podcast'],
            ['name' => 'libitem_contextmenu', 'value' => '1', 'description' => 'Library item context menu',
                'level' => 0, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'library'],
            ['name' => 'upload_catalog_pattern', 'value' => '0', 'description' => 'Rename uploaded file according to catalog pattern',
                'level' => 100, 'type' => 'boolean', 'category' => 'system', 'subcategory' => 'upload'],
            ['name' => 'catalog_check_duplicate', 'value' => '0', 'description' => 'Check library item at import time and don\'t import duplicates',
                'level' => 100, 'type' => 'boolean', 'category' => 'system', 'subcategory' => 'catalog'],
            ['name' => 'browse_filter', 'value' => '1', 'description' => 'Show filter box on browse',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'library'],
            ['name' => 'sidebar_light', 'value' => '0', 'description' => 'Light sidebar by default',
                'level' => 25, 'type' => 'boolean', 'category' => 'interface', 'subcategory' => 'theme'],
            ['name' => 'custom_blankalbum', 'value' => '', 'description' => 'Custom blank album default image',
                'level' => 75, 'type' => 'string', 'category' => 'interface', 'subcategory' => 'custom'],
            ['name' => 'custom_blankmovie', 'value' => '', 'description' => 'Custom blank video default image',
                'level' => 75, 'type' => 'string', 'category' => 'interface', 'subcategory' => 'custom'],
            ['name' => 'libitem_browse_alpha', 'value' => '', 'description' => 'Alphabet browsing by default for following library items (album,artist,...)',
                'level' => 75, 'type' => 'string', 'category' => 'interface', 'subcategory' => 'library']);
        
        DB::table('preferences')->delete();

        foreach ($seeds as $seed) {
            DB::table('preferences')->insert([
            'name' => $seed['name'],
            'value' => $seed['value'],
            'description' => $seed['description'],
            'level' => $seed['level'],
            'type' => $seed['type'],
            'category' => $seed['category'],
            'subcategory' => $seed['subcategory']
        ]);
        }
    }
}
