version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 200
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
plugins:
  fixme:
    enabled: true
  phan:
    enabled: true
  phpcodesniffer:
    enabled: true
    checks:
      Generic Files LineLength TooLong:
        enabled: false
      PSR1 Methods CamelCapsMethodName NotCamelCaps:
        enabled: false
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
  sonar-php:
    enabled: true

