checks:
  php:
    code_rating: true
    duplication: true

build:
  environment:
    php:
      version: "8.5"
      ini:
        memory_limit: "-1"
        xdebug.mode: coverage
    node: "v24.17.0"

  dependencies:
    override:
      - command: "composer install --no-interaction --prefer-dist"
      - command: "npm install"
      - command: "npm run build"

  nodes:
    analysis:
      tests:
        override:
          - command: "php-scrutinizer-run"

    coverage:
      tests:
        override:
          - command: "XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=build/coverage-clover.xml tests"
            coverage:
              file: "build/coverage-clover.xml"
              format: "clover"

filter:
  excluded_paths:
    - "public/lib/components/*"
    - "public/themes/*"
    - "vendor/*"
    - "tests/*"
    - ".github/*"

  dependency_paths:
    - "public/lib/components/*"
    - "vendor/*"
