build:
    environment:
        php:
            version: "8.2"
            ini:
                memory_limit: "-1"
         node: v18.19.0
    nodes:
        coverage:
            tests:
                override:
                    - command: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover build/coverage-clover.xml tests
                      coverage:
                        file: build/coverage-clover.xml
                        format: clover
filter:
    excluded_paths:
        - 'public/lib/components/*'
        - 'vendor/*'
        - 'tests'
    paths: {  }
tools:
    php_mess_detector:
        enabled: true
        filter:
            excluded_paths:
                - 'public/lib/components/*'
                - 'vendor/*'
                - 'public/themes/*'
                - '.github.*'
            paths: {  }
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'public/lib/components/*'
                - 'vendor/*'
            paths: {  }
    php_analyzer:
        enabled: true
        extensions:
            - php
        dependency_paths:
            - 'public/lib/components/*'
            - 'vendor/*'
        filter:
            excluded_paths:
                - 'public/lib/components/*'
                - 'vendor/*'
                - 'public/themes/*'
            paths: {  }
        path_configs: {  }
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            excluded_paths:
                - 'public/lib/components/*'
                - 'vendor/*'
            paths: {  }
    php_loc:
        enabled: true
        excluded_dirs:
            - 'public/lib/components/*'
            - 'vendor/*'
