<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// add_podcast.phtml -- rendered by Ampache\Gui\Form\AddPodcastFormView

use Ampache\Module\Util\Ui;

/** @var Ampache\Gui\Form\AddPodcastFormView $this */
Ui::show_box_top(T_('Subscribe to Podcast'), 'box box_add_podcast'); ?>
<form name="podcast" method="post" action="<?php echo $this->e($this->getWebPath()); ?>/podcast.php?action=create">
<table class="tabledata">
<tr>
    <td><?php echo T_('Podcast Feed URL'); ?></td>
    <td><input type="text" name="feed" value="<?php echo $this->e($this->getFeed()); ?>" />
        <?php echo $this->raw($this->getError('feed')); ?>
    </td>
</tr>
<tr>
    <td><?php echo T_('Catalog'); ?></td>
    <td>
        <?php show_catalog_select('catalog', $this->getCatalogId(), '', false, 'podcast', 'local'); ?>
        <?php echo $this->raw($this->getError('catalog')); ?>
    </td>
</tr>
</table>
<div class="formValidation">
    <?php echo $this->raw($this->getFormToken('add_podcast')); ?>
    <input class="button" type="submit" value="<?php echo T_('Subscribe'); ?>" />
</div>
</form>
<?php Ui::show_box_bottom(); ?>