<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// cookie_disclaimer.phtml -- rendered by Ampache\Gui\Form\CookieDisclaimerView

/** @var Ampache\Gui\Form\CookieDisclaimerView $this */
?>
<h1><?php echo T_('Use of cookies by Ampache'); ?></h1>
<br />
<p>
<?php echo T_('Cookies are small text files that are placed on your computer by websites that you visit. They are widely used in order to make websites work, or work more efficiently, as well as to provide information to the owners of the site'); ?><br />
<?php echo T_('The table below explains the cookies we use and why'); ?><br />
</p>
<br /><br />

<table class="tabledata">
    <thead>
        <tr>
            <td>
                <h2><?php echo T_('Cookie'); ?></h2>
            </td>
            <td>
                <h2><?php echo T_('Name'); ?></h2>
            </td>
            <td>
                <h2><?php echo T_('Purpose'); ?></h2>
            </td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Session</td>
            <td><?php echo $this->e($this->getSessionName()); ?></td>
            <td><?php echo T_('Ampache session'); ?></td>
        </tr>
        <tr>
            <td>Session username</td>
            <td><?php echo $this->e($this->getSessionName()); ?>_user</td>
            <td><?php echo T_('Ampache session username (if authenticated, information only)'); ?></td>
        </tr>
        <tr>
            <td>Remember Me</td>
            <td><?php echo $this->e($this->getSessionName()); ?>_remember</td>
            <td><?php echo T_('Automatically authenticate users'); ?></td>
        </tr>
        <tr>
            <td>jPlayer volume</td>
            <td>jp_volume</td>
            <td><?php echo T_('Keep latest web player volume'); ?></td>
        </tr>
        <tr>
            <td>Browse [object_type] Column [column_index]</td>
            <td>mt_[object_type]_[column_index]</td>
            <td><?php echo T_('Show/Hide column [column_index] when browsing [object_type] objects'); ?></td>
        </tr>
        <tr>
            <td>Browse [object_type] Alpha</td>
            <td>browse_[object_type]_alpha</td>
            <td><?php echo T_('Use alphabet when browsing [object_type] objects'); ?></td>
        </tr>
        <tr>
            <td>Browse [object_type] Pages</td>
            <td>browse_[object_type]_pages</td>
            <td><?php echo T_('Use pages when browsing [object_type] objects'); ?></td>
        </tr>
        <tr>
            <td>Sidebar [menu_section]</td>
            <td>sb_[menu_section]</td>
            <td><?php echo T_('Collapse/Expand Sidebar [menu_section]'); ?></td>
        </tr>
        <tr>
            <td>Sidebar state</td>
            <td>sidebar_state</td>
            <td><?php echo T_('Collapse/Expand Sidebar'); ?></td>
        </tr>
    </tbody>
</table>