<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// import_podcasts.phtml -- rendered by Ampache\Gui\Form\ImportPodcastsFormView

/** @var Ampache\Gui\Form\ImportPodcastsFormView $this */
?>
<form name="podcast" method="post" enctype="multipart/form-data" action="<?php echo $this->e($this->getWebPath()); ?>/podcast.php?action=import_podcasts">
    <table class="tabledata">
        <tr>
            <td><?php echo T_('File'); ?> (<?php echo T_('Format: opml') ?>)</td>
            <td>
                <input type="file" id="podcast_import_file" name="import_file" value="" />
                <?php echo $this->raw($this->getError('import_file')); ?>
            </td>
        </tr>
        <tr>
            <td><?php echo T_('Catalog'); ?></td>
            <td>
                <?php show_catalog_select('catalog', $this->getCatalogId(), '', false, 'podcast', 'local'); ?>
                <?php echo $this->raw($this->getError('catalog')); ?>
            </td>
        </tr>
    </table>
    <div class="formValidation">
        <?php echo $this->raw($this->getFormToken('import_podcasts')); ?>
        <input class="button" type="submit" value="<?php echo T_('Import'); ?>" />
    </div>
</form>
