<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// localplay_add_instance.phtml -- rendered by Ampache\Gui\Form\LocalplayAddInstanceView

use Ampache\Module\Util\Ui;

/** @var Ampache\Gui\Form\LocalplayAddInstanceView $this */

Ui::show_box_top(T_('Add Localplay Instance'), 'box box_localplay_add_instance'); ?>
<form method="post" action="<?php echo $this->e($this->getWebPath()); ?>/localplay.php?action=add_instance" autocomplete="off">
<table class="tabledata">
<?php foreach ($this->getFields() as $key => $field) {
    $autocomplete = ($field['type'] === 'password') ? 'new-password' : 'off'; ?>
<tr>
    <td><?php echo $this->e($field['description']); ?></td>
    <td><input type="<?php echo $this->e($field['type']); ?>" name="<?php echo $this->e($key); ?>" autocomplete="<?php echo $autocomplete; ?>" /></td>
</tr>
<?php } ?>
</table>
    <div class="formValidation">
        <input type="submit" value="<?php echo T_('Add Instance'); ?>" />
  </div>
</form>
<?php Ui::show_box_bottom(); ?>
