<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// recent.phtml -- rendered by Ampache\Gui\Form\RecentFormView

use Ampache\Module\Util\Ui;

/** @var Ampache\Gui\Form\RecentFormView $this */
?>

<h3 class="box-title"><?php echo T_('Recent'); ?></h3>

<div class="category_options">
    <a class="category <?php echo ($this->getFilter() == 'recent_song') ? 'current' : ''; ?>" href="<?php echo $this->e($this->getWebPath()); ?>/stats.php?action=recent_song"><?php echo T_('Songs'); ?></a>
    <a class="category <?php echo ($this->getFilter() == 'recent_album_disk' || $this->getFilter() == 'recent_album') ? 'current' : ''; ?>" href="<?php echo $this->e($this->getWebPath()); ?>/stats.php?action=recent_<?php echo $this->e($this->getAlbumString()); ?>"><?php echo T_('Albums'); ?></a>
    <?php if ($this->isShowArtist() || $this->getFilter() == 'recent_artist') { ?>
        <a class="category <?php echo ($this->getFilter() == 'recent_artist') ? 'current' : ''; ?>" href="<?php echo $this->e($this->getWebPath()); ?>/stats.php?action=recent_artist"><?php echo T_('Artists'); ?></a>
    <?php } ?>
    <?php if ($this->isShowAlbumArtist() || !$this->isShowArtist() || $this->getFilter() == 'recent_album_artist') { ?>
        <a class="category <?php echo ($this->getFilter() == 'recent_album_artist') ? 'current' : ''; ?>" href="<?php echo $this->e($this->getWebPath()); ?>/stats.php?action=recent_album_artist"><?php echo T_('Album Artists'); ?></a>
    <?php } ?>
    <?php if ($this->isPodcastEnabled()) { ?>
        <a class="category <?php echo ($this->getFilter() == 'recent_podcast_episode') ? 'current' : ''; ?>" href="<?php echo $this->e($this->getWebPath()); ?>/stats.php?action=recent_podcast_episode"><?php echo T_('Podcast Episodes'); ?></a>
    <?php }
    if ($this->isVideoEnabled()) { ?>
        <a class="category <?php echo ($this->getFilter() == 'recent_video') ? 'current' : ''; ?>" href="<?php echo $this->e($this->getWebPath()); ?>/stats.php?action=recent_video"><?php echo T_('Videos'); ?></a>
    <?php } ?>
</div>
<div id="information_actions">
    <ul>
        <li>
            <?php if ($this->isByUser()) { ?>
                <a href="<?php echo $this->e($this->getWebPath()); ?>/stats.php?action=<?php echo $this->e($this->getFilter()); ?>&by_user=0">
                    <?php echo Ui::get_material_symbol('group', T_('Show All')); ?>
                    <?php echo T_('Show All'); ?>
                </a>
            <?php } else { ?>
                <a href="<?php echo $this->e($this->getWebPath()); ?>/stats.php?action=<?php echo $this->e($this->getFilter()); ?>&by_user=1">
                    <?php echo Ui::get_material_symbol('person', T_('Personal')); ?>
                    <?php echo T_('Personal'); ?>
                </a>
            <?php } ?>
</div>
