<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// edit/live_stream.phtml -- rendered by Ampache\Gui\Edit\Renderer\LiveStreamEditFormRenderer

/** @var Ampache\Gui\Edit\Renderer\LiveStreamEditFormRenderer $this */
?>
<div>
    <form method="post" id="edit_live_stream_<?php echo $this->e($this->getLiveStreamId()); ?>" class="edit_dialog_content">
        <table class="tabledata">
            <tr>
                <td class="edit_dialog_content_header"><?php echo T_('Name'); ?></td>
                <td><input type="text" name="name" value="<?php echo $this->e($this->getName()); ?>" autofocus /></td>
            </tr>
            <tr>
                <td class="edit_dialog_content_header"><?php echo T_('Stream URL'); ?></td>
                <td><input type="text" name="url" value="<?php echo $this->e($this->getUrl()); ?>" /></td>
            </tr>
            <tr>
                <td class="edit_dialog_content_header"><?php echo T_('Website'); ?></td>
                <td><input type="text" name="site_url" value="<?php echo $this->e($this->getSiteUrl()); ?>" /></td>
            </tr>
            <tr>
                <td class="edit_dialog_content_header"><?php echo T_('Codec'); ?></td>
                <td><input type="text" name="codec" value="<?php echo $this->e($this->getCodec()); ?>" /></td>
            </tr>
        </table>
        <input type="hidden" name="id" value="<?php echo $this->e($this->getLiveStreamId()); ?>" />
        <input type="hidden" name="type" value="live_stream_row" />
    </form>
</div>
