<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// artist_row.phtml -- rendered by Ampache\Gui\Artist\ArtistRowView

use Ampache\Module\Api\Ajax;
use Ampache\Module\Art\Art;
use Ampache\Module\Playback\Stream_Playlist;
use Ampache\Module\Statistics\Rating;
use Ampache\Module\Statistics\Userflag;
use Ampache\Module\Util\Ui;

/** @var Ampache\Gui\Artist\ArtistRowView $this */

$libitem = $this->getArtist();
$itemId  = $libitem->getId(); ?>
<td class="cel_play">
    <span class="cel_play_content">&nbsp;</span>
    <div class="cel_play_hover">
<?php if ($this->isShowDirectPlay()) {
    echo $this->raw(Ajax::button('?page=stream&action=directplay&object_type=artist&object_id=' . $itemId, 'play_circle', T_('Play'), 'play_artist_' . $itemId));

    if (Stream_Playlist::check_autoplay_next()) {
        echo $this->raw(Ajax::button('?page=stream&action=directplay&object_type=artist&object_id=' . $itemId . '&playnext=true', 'menu_open', T_('Play next'), 'nextplay_artist_' . $itemId));
    }

    if (Stream_Playlist::check_autoplay_append()) {
        echo $this->raw(Ajax::button('?page=stream&action=directplay&object_type=artist&object_id=' . $itemId . '&append=true', 'low_priority', T_('Play last'), 'addplay_artist_' . $itemId));
    }
} ?>
    </div>
</td>
<td class="<?php echo $this->e($this->getClassCover()); ?>">
    <?php Art::display('artist', $itemId, $this->e($libitem->get_fullname()), $this->getArtSize(), $this->getWebPath() . '/artists.php?action=show&artist=' . $itemId); ?>
</td>
<td class="<?php echo $this->e($this->getClassArtist()); ?>"><?php echo $this->raw($libitem->get_f_link()); ?></td>
<td class="cel_add">
    <span class="cel_item_add">
<?php if ($this->isShowPlaylistAdd()) {
    echo $this->raw(Ajax::button('?action=basket&type=artist&id=' . $itemId, 'new_window', T_('Add to Temporary Playlist'), 'add_artist_' . $itemId));
    echo $this->raw(Ajax::button('?action=basket&type=artist_random&id=' . $itemId, 'shuffle', T_('Random to Temporary Playlist'), 'random_artist_' . $itemId)); ?>
            <a id="add_to_playlist_<?php echo $itemId; ?>" onclick="showPlaylistDialog(event, 'artist', '<?php echo $itemId; ?>')">
                <?php echo $this->raw(Ui::get_material_symbol('playlist_add', Ui::get_add_to_list_label())); ?>
            </a>
        <?php } ?>
    </span>
</td>
<td class="cel_songs optional"><?php echo $this->e($libitem->song_count); ?></td>
<td class="cel_albums optional"><?php echo $this->e($libitem->get_album_count()); ?></td>
<td class="<?php echo $this->e($this->getClassTime()); ?> optional"><?php echo $this->e($libitem->get_f_time()); ?></td>
<?php if ($this->isShowPlayedTimes()) { ?>
    <td class="<?php echo $this->e($this->getClassCounter()); ?> optional"><?php echo $this->e($libitem->total_count); ?></td>
<?php }
if (!$this->isHideGenres()) { ?>
<td class="<?php echo $this->e($this->getClassTags()); ?>"><?php echo $this->raw($libitem->get_f_tags()); ?></td>
<?php }
if (!$this->isHideMoods()) { ?>
<td class="<?php echo $this->e($this->getClassMoods()); ?>"><?php echo $this->raw($libitem->get_f_moods()); ?></td>
<?php }
if ($this->isShowRatings()) { ?>
        <td class="cel_ratings">
            <div class="rating">
                <span class="cel_rating" id="rating_<?php echo $itemId; ?>_artist">
                    <?php echo $this->raw(Rating::show($itemId, 'artist')); ?>
                </span>
                <span class="cel_userflag" id="userflag_<?php echo $itemId; ?>_artist">
                    <?php echo $this->raw(Userflag::show($itemId, 'artist')); ?>
                </span>
            </div>
        </td>
    <?php } ?>
<td class="cel_action">
<?php if ($this->canPostShout()) { ?>
    <a href="<?php echo $this->e($this->getWebPath()); ?>/shout.php?action=show_add_shout&type=artist&id=<?php echo $itemId; ?>">
        <?php echo $this->raw(Ui::get_material_symbol('comment', T_('Post Shout'))); ?>
    </a>
<?php }
if ($this->canEdit()) { ?>
        <a id="edit_artist_<?php echo $itemId; ?>" onclick="showEditDialog('artist_row', '<?php echo $itemId; ?>', 'edit_artist_<?php echo $itemId; ?>', '<?php echo $this->raw(addslashes(T_('Artist Edit'))); ?>', 'artist_', '<?php echo '&browse_id=' . $this->getBrowseId(); ?>')">
        <?php echo $this->raw(Ui::get_material_symbol('edit', T_('Edit'))); ?>
        </a>
<?php }
if ($this->canDelete()) { ?>
        <a id="delete_artist_<?php echo $itemId; ?>" href="<?php echo $this->e($this->getWebPath()); ?>/artists.php?action=delete&artist_id=<?php echo $itemId; ?>">
            <?php echo $this->raw(Ui::get_material_symbol('close', T_('Delete'))); ?>
        </a>
    <?php } ?>
</td>
