<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// artist_info.phtml -- rendered by Ampache\Gui\Artist\ArtistInfoView

use Ampache\Module\Art\Art;

/** @var Ampache\Gui\Artist\ArtistInfoView $this */

$summary = $this->getSummary(); ?>
<div class="item_info">
    <?php $artistId = $this->getArtistIdWithArt();
if ($artistId !== null) {
    Art::display('artist', $artistId, $this->getArtistName(), $this->getArtSize(), null, true, false);
} ?>
    <div class="item_properties">
        <?php echo $this->e($this->getFormationDetails()); ?>
    </div>
</div>
<div id="item_summary">
    <?php if ($summary !== null) {
        echo $this->raw(nl2br($summary));
    } ?>
</div>
<script>
    $(document).ready(function(){
        $("a[rel^='prettyPhoto']").prettyPhoto({
            social_tools: false,
            deeplinking: false
        });
    });
</script>
