<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// broadcast_action.phtml -- rendered by Ampache\Gui\Broadcast\BroadcastActionView

use Ampache\Module\Api\Ajax;
use Ampache\Module\Util\Ui;

/** @var Ampache\Gui\Broadcast\BroadcastActionView $this */

$broadcastId = $this->getBroadcastId(); ?>
<div class="broadcast-action"><?php if ($broadcastId === null) { ?><a href="#" onclick="showBroadcastsDialog(event);"><?php echo $this->raw(Ui::get_material_symbol('cell_tower', T_('Broadcast'))); ?></a><?php } else {
    echo $this->raw(Ajax::button('?page=player&action=unbroadcast&broadcast_id=' . $broadcastId, 'cell_tower', T_('Unbroadcast'), 'broadcast_action'));
} ?></div>
