<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// catalog_export.phtml -- rendered by Ampache\Gui\Admin\CatalogExportView

use Ampache\Module\Util\Ui;

/** @var Ampache\Gui\Admin\CatalogExportView $this */

Ui::show_box_top(T_('Export Catalog'), 'box box_export'); ?>
<form name="export" action="<?php echo $this->e($this->getActionUrl()); ?>" method="post" enctype="multipart/form-data">
    <table class="tableform">
        <tr>
            <td><strong><?php echo T_('Catalog'); ?>:</strong></td>
            <td>
                <select id="export_catalog" name="export_catalog">
                    <option value=""><?php echo T_('All'); ?></option>
                    <?php foreach ($this->getCatalogs() as $catalog) { ?>
                    <option value="<?php echo $this->e($catalog->getId()); ?>"><?php echo $this->e($catalog->get_fullname()); ?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
        <tr>
            <td><strong><?php echo T_('Format'); ?>:</strong></td>
            <td>
                <select id="export_format" name="export_format">
                    <?php foreach ($this->getExportTypes() as $key => $label) { ?>
                    <option value="<?php echo $this->e($key); ?>"><?php echo $this->e($label); ?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
    </table>
    <div class="formValidation">
        <input type="submit" value="<?php echo T_('Export'); ?>" />
    </div>
</form>
<?php Ui::show_box_bottom(); ?>
