<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// dashboard_form.phtml -- rendered by Ampache\Gui\Browse\DashboardFormView

/** @var Ampache\Gui\Browse\DashboardFormView $this */
?>
<h3 class="box-title"><?php echo T_('Dashboards'); ?></h3>
<div class="category_options">
    <?php foreach ($this->getCategories() as $category) { ?>
    <a class="category <?php echo $category['current'] ? 'current' : ''; ?>" href="<?php echo $this->e($this->getWebPath()); ?>/mashup.php?action=<?php echo $this->e($category['action']); ?>">
        <?php echo $this->e($category['label']); ?>
    </a>
    <?php } ?>
</div>
