<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// edit_shout.phtml -- rendered by Ampache\Gui\Shout\EditShoutView

use Ampache\Module\Util\Ui;

/** @var Ampache\Gui\Shout\EditShoutView $this */

$shout = $this->getShout();
Ui::show_box_top(T_('Edit Existing Shoutbox Post')); ?>
<form method="post" enctype="multipart/form-data" action="<?php echo $this->e($this->getWebPath()); ?>/shout.php?action=edit_shout">
<input type="hidden" name="shout_id" value="<?php echo $shout->getId(); ?>" />
<table class="tabledata">
<tr>
    <td><strong><?php /* HINT: %1 Client link, %2 Object link */ printf(T_('Created by: %1$s for %2$s'), $this->raw($this->getClient()->get_f_link()), $this->raw($this->getObject()->get_f_link())); ?></strong>
<tr>
<tr>
    <td><strong><?php echo T_('Comment:'); ?></strong>
</tr>
<tr>
    <td><textarea rows="5" cols="70" maxlength="2000" name="comment" autofocus><?php echo $this->e($shout->getText()); ?></textarea></td>
</tr>
<tr>
    <td><input type="checkbox" name="sticky" <?php echo ($shout->isSticky()) ? 'checked' : ''; ?>/> <strong><?php echo T_('Stick this comment'); ?></strong></td>
</tr>
<tr>
    <td><input type="submit" value="<?php echo T_('Update'); ?>" /></td>
</tr>
</table>
</form>
<?php Ui::show_box_bottom(); ?>
