<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// hidden_genre_cloud.phtml -- rendered by Ampache\Gui\Genre\HiddenGenreCloudView

use Ampache\Module\Api\Ajax;
use Ampache\Module\Util\Ui;

/** @var Ampache\Gui\Genre\HiddenGenreCloudView $this */

echo $this->raw($this->getForm()->render());

Ajax::start_container('tag_filter');
foreach ($this->getGenres() as $genre) { ?>
    <div class="tag_container">
        <div class="tag_button">
            <span id="click_tag_hidden_<?php echo $this->e($genre['id']); ?>"><?php echo $this->e($genre['name']); ?></span>
        </div>
        <?php if ($this->mayEdit()) { ?>
        <div class="tag_actions">
            <ul>
                <li>
                    <a class="tag_hidden_edit" id="tag_hidden_row<?php echo $this->e($genre['id']); ?>" onclick="showEditDialog('tag_hidden_row', '<?php echo $this->e($genre['id']); ?>', 'edit_tag_hidden_<?php echo $this->e($genre['id']); ?>', '<?php echo addslashes(T_('Edit')); ?>', 'click_tag_', '<?php echo $this->e($this->getBrowseArgument()); ?>')">
                        <?php echo $this->raw(Ui::get_material_symbol('edit', T_('Edit'))); ?>
                    </a>
                </li>
                <li>
                    <a class="tag_hidden_delete" href="<?php echo $this->e($this->getAjaxUri()); ?>?page=tag&action=delete&tag_id=<?php echo $this->e($genre['id']); ?>" data-confirm="<?php echo T_('Do you really want to delete this Tag?'); ?>"><?php echo $this->raw(Ui::get_material_symbol('close', T_('Delete'))); ?></a>
                </li>
            </ul>
        </div>
        <?php } ?>
    </div>
<?php }
?>
<br /><br /><br />
<?php Ajax::end_container(); ?>
