<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// live_stream_row.phtml -- rendered by Ampache\Gui\LiveStream\LiveStreamRowView

use Ampache\Module\Api\Ajax;
use Ampache\Module\Playback\Stream_Playlist;
use Ampache\Module\Statistics\Rating;
use Ampache\Module\Statistics\Userflag;
use Ampache\Module\Util\Ui;

/** @var Ampache\Gui\LiveStream\LiveStreamRowView $this */

$libitem = $this->getLiveStream();
$itemId  = $libitem->getId(); ?>
<td class="cel_play">
    <span class="cel_play_content">&nbsp;</span>
    <div class="cel_play_hover">
<?php if ($this->isDirectplayEnabled()) {
    echo $this->raw(Ajax::button('?page=stream&action=directplay&object_type=live_stream&object_id=' . $itemId, 'play_circle', T_('Play'), 'play_live_stream_' . $itemId));

    if (Stream_Playlist::check_autoplay_next()) {
        echo $this->raw(Ajax::button('?page=stream&action=directplay&object_type=live_stream&object_id=' . $itemId . '&playnext=true', 'menu_open', T_('Play next'), 'nextplay_live_stream_' . $itemId));
    }

    if (Stream_Playlist::check_autoplay_append()) {
        echo $this->raw(Ajax::button('?page=stream&action=directplay&object_type=live_stream&object_id=' . $itemId . '&append=true', 'low_priority', T_('Play last'), 'addplay_live_stream_' . $itemId));
    }
} ?>
    </div>
</td>
<td class="<?php echo $this->e($this->getClassCover()); ?>">
    <?php $libitem->display_art($this->getArtSize()); ?>
</td>
<td class="cel_streamname"><?php echo $this->raw($libitem->get_f_link()); ?></td>
<td class="cel_add">
    <span class="cel_item_add">
        <?php echo $this->raw(Ajax::button('?action=basket&type=live_stream&id=' . $itemId, 'new_window', T_('Add to Temporary Playlist'), 'playlist_add_' . $itemId));
if ($this->canAddToPlaylist()) { ?>
            <a id="add_to_playlist_<?php echo $itemId; ?>" onclick="showPlaylistDialog(event, 'live_stream', '<?php echo $itemId; ?>')">
                <?php echo $this->raw(Ui::get_material_symbol('playlist_add', Ui::get_add_to_list_label())); ?>
            </a>
        <?php } ?>
    </span>
</td>
<td class="cel_siteurl"><a target="_blank" href="<?php echo $this->e($libitem->site_url); ?>"><?php echo $this->e($libitem->site_url); ?></a></td>
<td class="cel_codec"><?php echo $this->e($libitem->codec); ?></td>
<?php if ($this->isShowRatings()) { ?>
    <td class="cel_ratings">
        <div class="rating">
            <span class="cel_rating" id="rating_<?php echo $itemId; ?>_live_stream">
                <?php echo $this->raw(Rating::show($itemId, 'live_stream')); ?>
            </span>
            <span class="cel_userflag" id="userflag_<?php echo $itemId; ?>_live_stream">
                <?php echo $this->raw(Userflag::show($itemId, 'live_stream')); ?>
            </span>
        </div>
    </td>
<?php } ?>
<td class="cel_action">
<?php if ($this->canEdit()) { ?>
        <a id="edit_live_stream_<?php echo $itemId; ?>" onclick="showEditDialog('live_stream_row', '<?php echo $itemId; ?>', 'edit_live_stream_<?php echo $itemId; ?>', '<?php echo $this->raw(addslashes(T_('Live Stream Edit'))); ?>', 'live_stream_', '<?php echo '&browse_id=' . $this->getBrowseId(); ?>')">
            <?php echo $this->raw(Ui::get_material_symbol('edit', T_('Edit'))); ?>
        </a>
<?php }
if ($this->canDelete()) {
    echo $this->raw(Ajax::button('?page=browse&action=delete_object&type=live_stream&id=' . $itemId, 'close', T_('Delete'), 'delete_live_stream_' . $itemId, '', '', T_('Are you sure?')));
} ?>
</td>
