<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// missing_artist.phtml -- rendered by Ampache\Gui\Artist\MissingArtistView

use Ampache\Module\Api\Ajax;
use Ampache\Module\Util\Ui;

/** @var Ampache\Gui\Artist\MissingArtistView $this */

Ui::show_box_top($this->e($this->getName()), 'info-box');
if ($this->hasBiography()) {
    echo $this->raw(Ajax::observe('window', 'load', Ajax::action('?page=index&action=artist_info&fullname=' . rawurlencode($this->getName()), 'artist_info'))); ?>
    <div id="artist_biography">
        <?php echo T_('Loading...'); ?>
    </div>
<?php }
Ui::show_box_bottom();
if ($this->hasMissingAlbums()) {
    echo $this->raw(Ajax::observe('window', 'load', Ajax::action('?page=index&action=wanted_missing_albums&artist_mbid=' . $this->getMusicBrainzId(), 'missing_albums'))); ?>
    <div id="missing_albums"></div>
<?php } ?>
