<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// now_playing_video_row.phtml -- rendered by Ampache\Gui\NowPlaying\NowPlayingVideoRowView

use Ampache\Module\Statistics\Rating;
use Ampache\Module\Statistics\Userflag;

/** @var Ampache\Gui\NowPlaying\NowPlayingVideoRowView $this */

$videoId = $this->getVideoId(); ?>
<div class="np_group" id="np_group_1">
    <div class="np_cell cel_username">
        <label><?php echo T_('Username'); ?></label>
        <a title="<?php echo $this->e($this->getAgent()); ?>" href="<?php echo $this->e($this->getClientUrl()); ?>">
            <?php echo $this->e($this->getClientName()); ?>
            <div><?php echo $this->raw($this->getAvatar()); ?></div>
        </a>
    </div>
</div>
<div class="np_group" id="np_group_2">
    <div class="np_cell cel_video">
        <label><?php echo T_('Video'); ?></label>
        <?php echo $this->raw($this->getVideoLink()); ?>
    </div>
</div>
<div class="np_group" id="np_group_3">
    <div class="np_cell cel_video"><?php echo $this->raw($this->getArt()); ?></div>
</div>
<div class="np_group" id="np_group_4">
    <?php if ($this->showRatings()) { ?>
    <span id="rating_<?php echo $videoId; ?>_video"><?php echo $this->raw(Rating::show($videoId, 'video')); ?></span>
    <span id="userflag_<?php echo $videoId; ?>_video"><?php echo $this->raw(Userflag::show($videoId, 'video')); ?></span>
    <?php } ?>
</div>
