<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// podcast_row.phtml -- rendered by Ampache\Gui\Podcast\PodcastRowView

use Ampache\Module\Api\Ajax;
use Ampache\Module\Art\Art;
use Ampache\Module\Playback\Stream_Playlist;
use Ampache\Module\Statistics\Rating;
use Ampache\Module\Statistics\Userflag;
use Ampache\Module\Util\Ui;

/** @var Ampache\Gui\Podcast\PodcastRowView $this */

$libitem = $this->getPodcast();
$itemId  = $libitem->getId(); ?>
<td class="cel_play">
    <span class="cel_play_content">&nbsp;</span>
    <div class="cel_play_hover">
<?php if ($this->isDirectplayEnabled()) {
    echo $this->raw(Ajax::button('?page=stream&action=directplay&object_type=podcast&object_id=' . $itemId, 'play_circle', T_('Play'), 'play_podcast_' . $itemId));

    if (Stream_Playlist::check_autoplay_next()) {
        echo $this->raw(Ajax::button('?page=stream&action=directplay&object_type=podcast&object_id=' . $itemId . '&playnext=true', 'menu_open', T_('Play next'), 'nextplay_podcast_' . $itemId));
    }

    if (Stream_Playlist::check_autoplay_append()) {
        echo $this->raw(Ajax::button('?page=stream&action=directplay&object_type=podcast&object_id=' . $itemId . '&append=true', 'low_priority', T_('Play last'), 'addplay_podcast_' . $itemId));
    }
} ?>
    </div>
</td>
<td class="<?php echo $this->e($this->getClassCover()); ?>">
    <?php Art::display('podcast', $itemId, (string) $libitem->get_fullname(), ['width' => 128, 'height' => 128], $libitem->get_link()); ?>
</td>
<td class="cel_title"><?php echo $this->raw($libitem->get_f_link()); ?></td>
<td class="cel_add">
    <span class="cel_item_add">
<?php echo $this->raw(Ajax::button('?action=basket&type=podcast&id=' . $itemId, 'new_window', T_('Add to Temporary Playlist'), 'add_podcast_' . $itemId));
if ($this->canAddToPlaylist()) { ?>
        <a id="add_to_playlist_podcast_<?php echo $itemId; ?>" onclick="showPlaylistDialog(event, 'podcast', '<?php echo $itemId; ?>')">
            <?php echo $this->raw(Ui::get_material_symbol('playlist_add', Ui::get_add_to_list_label())); ?>
        </a>
    <?php } ?>
    </span>
</td>
<td class="cel_siteurl"><a target="_blank" href="<?php echo $this->e($libitem->getWebsite()); ?>"><?php echo $this->e($libitem->getWebsite()); ?></a></td>
<td class="cel_episodes"><?php echo $this->e($libitem->getEpisodeCount()); ?></td>
<?php if ($this->isShowPlayedTimes()) { ?>
    <td class="<?php echo $this->e($this->getClassCounter()); ?> optional"><?php echo $this->e($libitem->getTotalCount()); ?></td>
<?php }
if ($this->isShowRatings()) { ?>
        <td class="cel_ratings">
            <div class="rating">
                <span class="cel_rating" id="rating_<?php echo $itemId; ?>_podcast"><?php echo $this->raw(Rating::show($itemId, 'podcast')); ?></span>
                <span class="cel_userflag" id="userflag_<?php echo $itemId; ?>_podcast"><?php echo $this->raw(Userflag::show($itemId, 'podcast')); ?></span>
            </div>
        </td>
    <?php } ?>
<td class="cel_action">
<?php if ($this->canEdit()) { ?>
    <a id="edit_podcast_<?php echo $itemId; ?>" onclick="showEditDialog('podcast_row', '<?php echo $itemId; ?>', 'edit_podcast_<?php echo $itemId; ?>', '<?php echo $this->raw(addslashes(T_('Podcast Edit'))); ?>', 'podcast_')">
        <?php echo $this->raw(Ui::get_material_symbol('edit', T_('Edit'))); ?>
    </a>
    <span id="button_sync_<?php echo $itemId; ?>">
        <?php echo $this->raw(Ajax::button('?page=podcast&action=syncPodcast&podcast_id=' . $itemId, 'sync', T_('Sync'), 'sync_podcast_' . $itemId)); ?>
    </span>
<?php }
if ($this->canDelete()) { ?>
    <a id="delete_podcast_<?php echo $itemId; ?>" href="<?php echo $this->e($this->getWebPath()); ?>/podcast.php?action=delete&podcast_id=<?php echo $itemId; ?>">
        <?php echo $this->raw(Ui::get_material_symbol('close', T_('Delete'))); ?>
    </a>
    <?php } ?>
</td>
