<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// stats.phtml -- rendered by Ampache\Gui\Stats\StatsViewAdapter

/** @var Ampache\Gui\Stats\StatsViewAdapter $this */

$catalogStats = $this->getCatalogStats(); ?>
<em><?php echo T_('Catalogs'); ?></em>
<table class="tabledata">
    <thead>
    <tr class="th-top">
        <th><?php echo T_('Connected Users'); ?></th>
        <th><?php echo T_('Total Users'); ?></th>
        <th><?php echo T_('Albums'); ?></th>
        <th><?php echo T_('Artists'); ?></th>
        <th><?php echo T_('Songs'); ?></th>
<?php if ($this->displayVideo()) { ?>
        <th><?php echo T_('Videos'); ?></th>
<?php }
if ($this->displayPodcast()) { ?>
        <th><?php echo T_('Podcasts'); ?></th>
        <th><?php echo T_('Podcast Episodes'); ?></th>
<?php } ?>
        <th><?php echo T_('Genres'); ?></th>
        <th><?php echo T_('Catalog Size'); ?></th>
        <th><?php echo T_('Catalog Time'); ?></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><?php echo $this->e($catalogStats->getConnectedCount()); ?></td>
        <td><?php echo $this->e($catalogStats->getUserCount()); ?></td>
<?php if ($this->displayAlbumDisk()) { ?>
        <td><?php echo $this->e($catalogStats->getAlbumDiskCount()); ?></td>
<?php }
if ($this->displayAlbum()) { ?>
        <td><?php echo $this->e($catalogStats->getAlbumCount()); ?></td>
<?php } ?>
        <td><?php echo $this->e($catalogStats->getArtistCount()); ?></td>
        <td><?php echo $this->e($catalogStats->getSongCount()); ?></td>
<?php if ($this->displayVideo()) { ?>
        <td><?php echo $this->e($catalogStats->getVideoCount()); ?></td>
<?php }
if ($this->displayPodcast()) { ?>
        <td><?php echo $this->e($catalogStats->getPodcastCount()); ?></td>
        <td><?php echo $this->e($catalogStats->getPodcastEpisodeCount()); ?></td>
<?php } ?>
        <td><?php echo $this->e($catalogStats->getGenreCount()); ?></td>
        <td><?php echo $this->e($catalogStats->getCatalogSize()); ?></td>
        <td><?php echo $this->e($catalogStats->getPlayTime()); ?></td>
    </tr>
    </tbody>
</table>
<hr />
<table class="tabledata">
    <colgroup>
        <col id="col_catalog" />
        <col id="col_path" />
        <col id="col_lastverify" />
        <col id="col_lastadd" />
        <col id="col_lastclean" />
        <col id="cel_items" />
        <col id="col_total" />
    </colgroup>
    <thead>
    <tr class="th-top">
        <th class="cel_catalog"><?php echo T_('Name'); ?></th>
        <th class="cel_path"><?php echo T_('Path'); ?></th>
        <th class="cel_lastverify"><?php echo T_('Last Verify'); ?></th>
        <th class="cel_lastadd"><?php echo T_('Last Add'); ?></th>
        <th class="cel_lastclean"><?php echo T_('Last Clean'); ?></th>
        <th class="cel_items"><?php echo T_('Item Count'); ?></th>
        <th class="cel_total"><?php echo T_('Catalog Size'); ?></th>
    </tr>
    </thead>
    <tbody>
<?php foreach ($this->getCatalogDetails() as $catalog) {
    $detailStats = $catalog->getCatalogStats(); ?>
    <tr>
        <td class="cel_catalog"><?php echo $this->e($catalog->getName()); ?></td>
        <td class="cel_path"><?php echo $this->raw($catalog->getFullInfo()); ?></td>
        <td class="cel_lastverify"><?php echo $this->raw($catalog->getLastUpdateDate()); ?></td>
        <td class="cel_lastadd"><?php echo $this->raw($catalog->getLastAddDate()); ?></td>
        <td class="cel_lastclean"><?php echo $this->raw($catalog->getLastCleanDate()); ?></td>
        <td class="cel_items"><?php echo $this->e($detailStats->getItemCount()); ?></td>
        <td class="cel_total"><?php echo $this->e($detailStats->getCatalogSize()); ?></td>
    </tr>
<?php } ?>
    </tbody>
</table>
