<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// update.phtml -- rendered by Ampache\Gui\System\UpdateViewAdapter

/** @var Ampache\Gui\System\UpdateViewAdapter $this */

?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->e($this->getHtmlLanguage()); ?>" lang="<?php echo $this->e($this->getHtmlLanguage()); ?>">
<head>
    <!-- Propelled by Ampache | ampache.org -->
    <meta http-equiv="Content-Type" content="text/html; charset=<?php echo $this->e($this->getCharset()); ?>" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><?php echo $this->e($this->getTitle()); ?></title>
    <link rel="stylesheet" href="lib/components/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="templates/install.css" type="text/css" media="screen" />
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container" style="height: 70px;">
        <a class="navbar-brand" href="#">
            <img src="<?php echo $this->e($this->getLogoUrl()); ?>" title="<?php echo $this->e(T_('Ampache')); ?>" alt="<?php echo $this->e(T_('Ampache')); ?>" />
            <?php echo $this->e($this->getInstallationTitle()); ?>
        </a>
    </div>
</div>
<div class="container" role="main">
    <div class="page-header requirements">
        <h1><?php echo T_('Ampache Update'); ?></h1>
    </div>
    <div class="well">
        <p><?php echo $this->raw($this->getUpdateInfoText()); ?></p>
        <p><?php echo T_('The following updates need to be performed:'); ?></p>
    </div>
    <?php echo $this->raw($this->getErrorText()); ?>
<?php if (!$this->hasUpdate()) { ?>
    <div class="content">
        <p class="database-update">No Update Needed [<a href="<?php echo $this->e($this->getWebPath()); ?>">Return to main page</a>]</p>
    </div>
<?php } else { ?>
    <div class="content">
        <ul>
<?php   foreach ($this->getUpdateInfo() as $update) { ?>
            <li style="margin-bottom: 10px">
                <strong><?php echo $this->e($update['title']); ?></strong><br />
<?php       if ($update['warning']) { ?>
                <div>
                    <h4><?php echo T_('Warning'); ?></h4>
                    Please consider using the CLI for this update (`php bin/cli admin:updateDatabase -e`) <a href="https://ampache.org/docs/help/cli-update-warning">Ampache Wiki</a>,
                </div>
<?php       } ?>
                <ul>
<?php       foreach ($update['changelog'] as $line) { ?>
                   <li><?php echo $this->e($line); ?></li>
<?php       } ?>
                </ul>
            </li>
<?php   } ?>
        </ul>
    </div>
    <form method="post" enctype="multipart/form-data" action="<?php echo $this->e($this->getUpdateActionUrl()); ?>">
        <button type="submit" class="btn btn-warning" name="update"><?php echo T_('Update Now!'); ?></button>
    </form>
<?php } ?>
</div>
</body>
</html>
