<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// user_preferences.phtml -- rendered by Ampache\Gui\Admin\UserPreferencesView

use Ampache\Module\System\Core;
use Ampache\Module\Util\Ui;

/** @var Ampache\Gui\Admin\UserPreferencesView $this */

Ui::show_box_top($this->getTitle(), 'box box_preferences'); ?>
<form method="post" name="preferences" action="<?php echo $this->e($this->getActionUrl()); ?>" enctype="multipart/form-data">
<table class="tabledata striped-rows">
<colgroup>
    <col id="col_preference" />
    <col id="col_value" />
</colgroup>
<tr class="th-top">
    <th class="col_preference"><?php echo T_('Preference'); ?></th>
    <th class="col_value"><?php echo T_('Value'); ?></th>
</tr>
<?php foreach ($this->getPreferences() as $preference) { ?>
<tr>
    <td class="cel_preference"><?php echo $this->e(T_($preference['description'])); ?></td>
    <td class="cel_value"><?php echo $this->raw($this->renderInput($preference['name'], $preference['value'])); ?></td>
</tr>
<?php } ?>
<tr>
    <td>
    <div class="formValidation">
    <input class="button" type="submit" value="<?php echo T_('Update Preferences'); ?>" />
    <?php echo $this->raw(Core::form_register('update_preference')); ?>
    <input type="hidden" name="user_id" value="<?php echo $this->e($this->getClientId()); ?>" />
    </div>
    </td>
    <td>&nbsp;</td>
</tr>
</table>
</form>
<?php Ui::show_box_bottom(); ?>
