<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// video_row.phtml -- rendered by Ampache\Gui\Video\VideoRowView

use Ampache\Module\Api\Ajax;
use Ampache\Module\Art\Art;
use Ampache\Module\Playback\Stream_Playlist;
use Ampache\Module\Statistics\Rating;
use Ampache\Module\Statistics\Userflag;
use Ampache\Module\Util\Ui;
use Ampache\Repository\Model\Share;

/** @var Ampache\Gui\Video\VideoRowView $this */

$libitem = $this->getVideo();
$itemId  = $libitem->getId(); ?>
<td class="cel_play">
    <span class="cel_play_content">&nbsp;</span>
    <div class="cel_play_hover">
<?php if ($this->isDirectplayEnabled()) {
    echo $this->raw(Ajax::button('?page=stream&action=directplay&object_type=video&object_id=' . $itemId, 'play_circle', T_('Play'), 'play_video_' . $itemId));

    if (Stream_Playlist::check_autoplay_next()) {
        echo $this->raw(Ajax::button('?page=stream&action=directplay&object_type=video&object_id=' . $itemId . '&playnext=true', 'menu_open', T_('Play next'), 'nextplay_video_' . $itemId));
    }

    if (Stream_Playlist::check_autoplay_append()) {
        echo $this->raw(Ajax::button('?page=stream&action=directplay&object_type=video&object_id=' . $itemId . '&append=true', 'low_priority', T_('Play last'), 'addplay_video_' . $itemId));
    }
} ?>
    </div>
</td>
<td class="<?php echo $this->e($this->getClassCover()); ?>">
    <?php $art_showed = false;
if ($libitem->get_default_art_kind() == 'preview') {
    $art_showed = Art::display('video', $itemId, (string) $libitem->get_fullname(), ['width' => 150, 'height' => 84], $libitem->get_link(), false, true, 'preview');
}

if (!$art_showed) {
    Art::display('video', $itemId, (string) $libitem->get_fullname(), $this->getArtSize(), $libitem->get_link());
} ?>
</td>
<td class="cel_title"><?php echo $this->raw($libitem->get_f_link()); ?></td>
<td class="cel_add">
    <span class="cel_item_add">
<?php echo $this->raw(Ajax::button('?action=basket&type=video&id=' . $itemId, 'new_window', T_('Add to Temporary Playlist'), 'add_' . $itemId));
if ($this->canAddToPlaylist()) { ?>
        <a id="add_to_playlist_<?php echo $itemId; ?>" onclick="showPlaylistDialog(event, 'video', '<?php echo $itemId; ?>')">
            <?php echo $this->raw(Ui::get_material_symbol('playlist_add', Ui::get_add_to_list_label())); ?>
        </a>
    <?php } ?>
    </span>
</td>
<td class="cel_release_date"><?php echo $this->e(($libitem->release_date) ? get_datetime((int) $libitem->release_date, 'short', 'none') : ''); ?></td>
<td class="cel_codec"><?php echo $this->e($libitem->video_codec . ' / ' . $libitem->audio_codec); ?></td>
<td class="cel_resolution"><?php echo $this->e($libitem->get_f_resolution()); ?></td>
<td class="cel_length"><?php echo $this->e(floor($libitem->time / 60) . ' ' . T_('minutes')); ?></td>
<?php if ($this->isShowPlayedTimes()) { ?>
<td class="<?php echo $this->e($this->getClassCounter()); ?>"><?php echo $this->e($libitem->total_count); ?></td>
<?php }
if (!$this->isHideGenres()) { ?>
<td class="<?php echo $this->e($this->getClassTags()); ?>"><?php echo $this->raw($libitem->get_f_tags()); ?></td>
<?php }
if (!$this->isHideMoods()) { ?>
<td class="<?php echo $this->e($this->getClassMoods()); ?>"><?php echo $this->raw($libitem->get_f_moods()); ?></td>
<?php }
if ($this->isShowRatings()) { ?>
        <td class="cel_ratings">
            <div class="rating">
                <span class="cel_rating" id="rating_<?php echo $itemId; ?>_video">
                    <?php echo $this->raw(Rating::show($itemId, 'video')); ?>
                </span>
                <span class="cel_userflag" id="userflag_<?php echo $itemId; ?>_video">
                    <?php echo $this->raw(Userflag::show($itemId, 'video')); ?>
                </span>
            </div>
        </td>
    <?php } ?>
<td class="cel_action">
<a href="<?php echo $this->e($libitem->get_link()); ?>"><?php echo $this->raw(Ui::get_material_symbol('page_info', T_('Video Information'))); ?></a>
<?php if ($this->canPostShout()) { ?>
        <a href="<?php echo $this->e($this->getWebPath()); ?>/shout.php?action=show_add_shout&type=video&id=<?php echo $itemId; ?>"><?php echo $this->raw(Ui::get_material_symbol('comment', T_('Post Shout'))); ?></a>
<?php }
if ($this->canShare()) {
    echo $this->raw(Share::display_ui('video', $itemId, false));
} else {
    $link = "&nbsp;" . T_('Link'); ?>
    <li>
        <a href="<?php echo $this->e($libitem->get_link()); ?>" target=_blank>
            <?php echo $this->raw(Ui::get_material_symbol('open_in_new', $link));
    echo $this->raw($link); ?>
        </a>
    </li>
<?php }
if ($this->canDownload()) { ?>
    <a class="nohtml" href="<?php echo $this->e($this->getWebPath()); ?>/stream.php?action=download&video_id=<?php echo $itemId; ?>" rel="nofollow"><?php echo $this->raw(Ui::get_material_symbol('download', T_('Download'))); ?></a>
<?php }
if ($this->canEdit()) { ?>
    <a id="edit_video_<?php echo $itemId; ?>" onclick="showEditDialog('video_row', '<?php echo $itemId; ?>', 'edit_video_<?php echo $itemId; ?>', '<?php echo $this->raw(addslashes(T_('Video Edit'))); ?>', 'video_', '<?php echo '&browse_id=' . $this->getBrowseId(); ?>')">
        <?php echo $this->raw(Ui::get_material_symbol('edit', T_('Edit'))); ?>
    </a>
<?php }
if ($this->canDelete()) { ?>
    <a id="delete_video_<?php echo $itemId; ?>" href="<?php echo $this->e($this->getWebPath()); ?>/video.php?action=delete&video_id=<?php echo $itemId; ?>">
        <?php echo $this->raw(Ui::get_material_symbol('close', T_('Delete'))); ?>
    </a>
<?php } ?>
</td>
