<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// wanted_album_row.phtml -- rendered by Ampache\Gui\Wanted\WantedAlbumRowView

/** @var Ampache\Gui\Wanted\WantedAlbumRowView $this */

$item = $this->getItem(); ?>
<td class="cel_album"><?php echo $this->raw($item->get_f_link()); ?></td>
<td class="cel_artist"><?php echo $this->raw($item->get_f_parent_link() ?? ''); ?></td>
<td class="cel_year"><?php echo $this->e($item->year); ?></td>
<td class="cel_user"><?php echo $this->raw($item->get_f_user()); ?></td>
<td class="cel_action">
    <div id="wanted_action_<?php echo $this->e($item->mbid); ?>">
    <?php echo $this->raw($item->show_action_buttons()); ?>
    </div>
</td>
