<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// export.phtml -- rendered by Ampache\Module\Podcast\Exchange\PodcastOpmlView

/** @var Ampache\Module\Podcast\Exchange\PodcastOpmlView $this */

echo '<?xml version="1.0" encoding="UTF-8"?>', "\n"; ?>
<opml version="2.0">
    <head>
        <title><?php echo $this->e($this->getTitle()); ?></title>
        <dateCreated><?php echo $this->e($this->getCreationDate()); ?></dateCreated>
    </head>
    <body>
<?php foreach ($this->getPodcasts() as $podcast) { ?>
        <outline text="<?php echo $this->e($podcast['title']); ?>" language="<?php echo $this->e($podcast['language']); ?>" description="<?php echo $this->e($podcast['description']); ?>" xmlUrl="<?php echo $this->e($podcast['feedUrl']); ?>" htmlUrl="<?php echo $this->e($podcast['website']); ?>"/>
<?php } ?>
    </body>
</opml>
