<?php

declare(strict_types=1);

/**
 * vim:set softtabstop=4 shiftwidth=4 expandtab:
 *
 * LICENSE: GNU Affero General Public License, version 3 (AGPL-3.0-or-later)
 * Copyright Ampache.org, 2001-2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

// partial/top_menu.phtml -- rendered by Ampache\Gui\Partial\TopMenuView

use Ampache\Module\Util\Ui;

/** @var Ampache\Gui\Partial\TopMenuView $this */

$webPath = $this->getWebPath(); ?>
<div id="topmenu_container" class="<?php echo $this->e($this->getContainerClass()); ?>">
    <?php foreach ($this->getItems() as $item) { ?>
    <div class="topmenu_item">
        <a href="<?php echo $this->e($webPath . $item['url']); ?>"<?php echo ($item['target']) ? ' target="_top" class="nohtml"' : ''; ?>>
            <?php echo $this->raw(Ui::get_image($item['icon'], $item['label'])); ?>
            <span><?php echo $this->e($item['label']); ?></span>
        </a>
    </div>
    <?php } ?>
</div>
